/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as JobsRouteRouteImport } from './routes/jobs/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as StaffSignInRouteImport } from './routes/staff/sign-in'
import { Route as JobsSlugRouteImport } from './routes/jobs/$slug'
import { Route as HireSignUpRouteImport } from './routes/hire/sign-up'
import { Route as HireSignInRouteImport } from './routes/hire/sign-in'
import { Route as ApplySignUpRouteImport } from './routes/apply/sign-up'
import { Route as ApplySignInRouteImport } from './routes/apply/sign-in'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedRecruiterRouteRouteImport } from './routes/_authenticated/recruiter/route'
import { Route as AuthenticatedCandidateRouteRouteImport } from './routes/_authenticated/candidate/route'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRecruiterIndexRouteImport } from './routes/_authenticated/recruiter/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCandidateIndexRouteImport } from './routes/_authenticated/candidate/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCandidateResumeRouteImport } from './routes/_authenticated/candidate/resume'
import { Route as AuthenticatedCandidateProfileRouteImport } from './routes/_authenticated/candidate/profile'
import { Route as AuthenticatedCandidateApplicationsRouteImport } from './routes/_authenticated/candidate/applications'
import { Route as AuthenticatedRecruiterPricingIndexRouteImport } from './routes/_authenticated/recruiter/pricing/index'
import { Route as AuthenticatedAdminRevenueIndexRouteImport } from './routes/_authenticated/admin/revenue/index'
import { Route as AuthenticatedAdminRecruitersIndexRouteImport } from './routes/_authenticated/admin/recruiters/index'
import { Route as AuthenticatedAdminJobsIndexRouteImport } from './routes/_authenticated/admin/jobs/index'
import { Route as AuthenticatedAdminEmailIndexRouteImport } from './routes/_authenticated/admin/email/index'
import { Route as AuthenticatedAdminCandidatesIndexRouteImport } from './routes/_authenticated/admin/candidates/index'
import { Route as AuthenticatedAdminCampaignsIndexRouteImport } from './routes/_authenticated/admin/campaigns/index'
import { Route as AuthenticatedRecruiterJobsNewRouteImport } from './routes/_authenticated/recruiter/jobs/new'
import { Route as AuthenticatedAdminSettingsEmailRouteImport } from './routes/_authenticated/admin/settings/email'
import { Route as AuthenticatedAdminEmailTestRouteImport } from './routes/_authenticated/admin/email/test'
import { Route as AuthenticatedAdminEmailAutomationsRouteImport } from './routes/_authenticated/admin/email/automations'
import { Route as AuthenticatedAdminEmailAnalyticsRouteImport } from './routes/_authenticated/admin/email/analytics'
import { Route as AuthenticatedAdminEmailTemplatesIndexRouteImport } from './routes/_authenticated/admin/email/templates/index'
import { Route as AuthenticatedAdminEmailCampaignsIndexRouteImport } from './routes/_authenticated/admin/email/campaigns/index'
import { Route as AuthenticatedRecruiterJobsJobIdEditRouteImport } from './routes/_authenticated/recruiter/jobs/$jobId/edit'
import { Route as AuthenticatedRecruiterJobsJobIdApplicantsRouteImport } from './routes/_authenticated/recruiter/jobs/$jobId/applicants'
import { Route as AuthenticatedAdminEmailTemplatesTemplateIdRouteImport } from './routes/_authenticated/admin/email/templates/$templateId'
import { Route as AuthenticatedAdminEmailCampaignsNewRouteImport } from './routes/_authenticated/admin/email/campaigns/new'
import { Route as AuthenticatedAdminEmailCampaignsCampaignIdRouteImport } from './routes/_authenticated/admin/email/campaigns/$campaignId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRouteRoute = JobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRouteRoute,
} as any)
const StaffSignInRoute = StaffSignInRouteImport.update({
  id: '/staff/sign-in',
  path: '/staff/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRouteRoute,
} as any)
const HireSignUpRoute = HireSignUpRouteImport.update({
  id: '/hire/sign-up',
  path: '/hire/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const HireSignInRoute = HireSignInRouteImport.update({
  id: '/hire/sign-in',
  path: '/hire/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySignUpRoute = ApplySignUpRouteImport.update({
  id: '/apply/sign-up',
  path: '/apply/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySignInRoute = ApplySignInRouteImport.update({
  id: '/apply/sign-in',
  path: '/apply/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterRouteRoute =
  AuthenticatedRecruiterRouteRouteImport.update({
    id: '/recruiter',
    path: '/recruiter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateRouteRoute =
  AuthenticatedCandidateRouteRouteImport.update({
    id: '/candidate',
    path: '/candidate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRecruiterIndexRoute =
  AuthenticatedRecruiterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidateIndexRoute =
  AuthenticatedCandidateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateResumeRoute =
  AuthenticatedCandidateResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateProfileRoute =
  AuthenticatedCandidateProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateApplicationsRoute =
  AuthenticatedCandidateApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedRecruiterPricingIndexRoute =
  AuthenticatedRecruiterPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedAdminRevenueIndexRoute =
  AuthenticatedAdminRevenueIndexRouteImport.update({
    id: '/revenue/',
    path: '/revenue/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRecruitersIndexRoute =
  AuthenticatedAdminRecruitersIndexRouteImport.update({
    id: '/recruiters/',
    path: '/recruiters/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminJobsIndexRoute =
  AuthenticatedAdminJobsIndexRouteImport.update({
    id: '/jobs/',
    path: '/jobs/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailIndexRoute =
  AuthenticatedAdminEmailIndexRouteImport.update({
    id: '/email/',
    path: '/email/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCandidatesIndexRoute =
  AuthenticatedAdminCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCampaignsIndexRoute =
  AuthenticatedAdminCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsNewRoute =
  AuthenticatedRecruiterJobsNewRouteImport.update({
    id: '/jobs/new',
    path: '/jobs/new',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedAdminSettingsEmailRoute =
  AuthenticatedAdminSettingsEmailRouteImport.update({
    id: '/settings/email',
    path: '/settings/email',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailTestRoute =
  AuthenticatedAdminEmailTestRouteImport.update({
    id: '/email/test',
    path: '/email/test',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailAutomationsRoute =
  AuthenticatedAdminEmailAutomationsRouteImport.update({
    id: '/email/automations',
    path: '/email/automations',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailAnalyticsRoute =
  AuthenticatedAdminEmailAnalyticsRouteImport.update({
    id: '/email/analytics',
    path: '/email/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailTemplatesIndexRoute =
  AuthenticatedAdminEmailTemplatesIndexRouteImport.update({
    id: '/email/templates/',
    path: '/email/templates/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailCampaignsIndexRoute =
  AuthenticatedAdminEmailCampaignsIndexRouteImport.update({
    id: '/email/campaigns/',
    path: '/email/campaigns/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsJobIdEditRoute =
  AuthenticatedRecruiterJobsJobIdEditRouteImport.update({
    id: '/jobs/$jobId/edit',
    path: '/jobs/$jobId/edit',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedRecruiterJobsJobIdApplicantsRoute =
  AuthenticatedRecruiterJobsJobIdApplicantsRouteImport.update({
    id: '/jobs/$jobId/applicants',
    path: '/jobs/$jobId/applicants',
    getParentRoute: () => AuthenticatedRecruiterRouteRoute,
  } as any)
const AuthenticatedAdminEmailTemplatesTemplateIdRoute =
  AuthenticatedAdminEmailTemplatesTemplateIdRouteImport.update({
    id: '/email/templates/$templateId',
    path: '/email/templates/$templateId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailCampaignsNewRoute =
  AuthenticatedAdminEmailCampaignsNewRouteImport.update({
    id: '/email/campaigns/new',
    path: '/email/campaigns/new',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailCampaignsCampaignIdRoute =
  AuthenticatedAdminEmailCampaignsCampaignIdRouteImport.update({
    id: '/email/campaigns/$campaignId',
    path: '/email/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/recruiter': typeof AuthenticatedRecruiterRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apply/sign-in': typeof ApplySignInRoute
  '/apply/sign-up': typeof ApplySignUpRoute
  '/hire/sign-in': typeof HireSignInRoute
  '/hire/sign-up': typeof HireSignUpRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/jobs/': typeof JobsIndexRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/resume': typeof AuthenticatedCandidateResumeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/admin/email/analytics': typeof AuthenticatedAdminEmailAnalyticsRoute
  '/admin/email/automations': typeof AuthenticatedAdminEmailAutomationsRoute
  '/admin/email/test': typeof AuthenticatedAdminEmailTestRoute
  '/admin/settings/email': typeof AuthenticatedAdminSettingsEmailRoute
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/admin/campaigns/': typeof AuthenticatedAdminCampaignsIndexRoute
  '/admin/candidates/': typeof AuthenticatedAdminCandidatesIndexRoute
  '/admin/email/': typeof AuthenticatedAdminEmailIndexRoute
  '/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/recruiters/': typeof AuthenticatedAdminRecruitersIndexRoute
  '/admin/revenue/': typeof AuthenticatedAdminRevenueIndexRoute
  '/recruiter/pricing/': typeof AuthenticatedRecruiterPricingIndexRoute
  '/admin/email/campaigns/$campaignId': typeof AuthenticatedAdminEmailCampaignsCampaignIdRoute
  '/admin/email/campaigns/new': typeof AuthenticatedAdminEmailCampaignsNewRoute
  '/admin/email/templates/$templateId': typeof AuthenticatedAdminEmailTemplatesTemplateIdRoute
  '/recruiter/jobs/$jobId/applicants': typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
  '/recruiter/jobs/$jobId/edit': typeof AuthenticatedRecruiterJobsJobIdEditRoute
  '/admin/email/campaigns/': typeof AuthenticatedAdminEmailCampaignsIndexRoute
  '/admin/email/templates/': typeof AuthenticatedAdminEmailTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apply/sign-in': typeof ApplySignInRoute
  '/apply/sign-up': typeof ApplySignUpRoute
  '/hire/sign-in': typeof HireSignInRoute
  '/hire/sign-up': typeof HireSignUpRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/jobs': typeof JobsIndexRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/resume': typeof AuthenticatedCandidateResumeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/candidate': typeof AuthenticatedCandidateIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/recruiter': typeof AuthenticatedRecruiterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/email/analytics': typeof AuthenticatedAdminEmailAnalyticsRoute
  '/admin/email/automations': typeof AuthenticatedAdminEmailAutomationsRoute
  '/admin/email/test': typeof AuthenticatedAdminEmailTestRoute
  '/admin/settings/email': typeof AuthenticatedAdminSettingsEmailRoute
  '/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsIndexRoute
  '/admin/candidates': typeof AuthenticatedAdminCandidatesIndexRoute
  '/admin/email': typeof AuthenticatedAdminEmailIndexRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsIndexRoute
  '/admin/recruiters': typeof AuthenticatedAdminRecruitersIndexRoute
  '/admin/revenue': typeof AuthenticatedAdminRevenueIndexRoute
  '/recruiter/pricing': typeof AuthenticatedRecruiterPricingIndexRoute
  '/admin/email/campaigns/$campaignId': typeof AuthenticatedAdminEmailCampaignsCampaignIdRoute
  '/admin/email/campaigns/new': typeof AuthenticatedAdminEmailCampaignsNewRoute
  '/admin/email/templates/$templateId': typeof AuthenticatedAdminEmailTemplatesTemplateIdRoute
  '/recruiter/jobs/$jobId/applicants': typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
  '/recruiter/jobs/$jobId/edit': typeof AuthenticatedRecruiterJobsJobIdEditRoute
  '/admin/email/campaigns': typeof AuthenticatedAdminEmailCampaignsIndexRoute
  '/admin/email/templates': typeof AuthenticatedAdminEmailTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/jobs': typeof JobsRouteRouteWithChildren
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/_authenticated/recruiter': typeof AuthenticatedRecruiterRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/apply/sign-in': typeof ApplySignInRoute
  '/apply/sign-up': typeof ApplySignUpRoute
  '/hire/sign-in': typeof HireSignInRoute
  '/hire/sign-up': typeof HireSignUpRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/_authenticated/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/_authenticated/candidate/resume': typeof AuthenticatedCandidateResumeRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/email/analytics': typeof AuthenticatedAdminEmailAnalyticsRoute
  '/_authenticated/admin/email/automations': typeof AuthenticatedAdminEmailAutomationsRoute
  '/_authenticated/admin/email/test': typeof AuthenticatedAdminEmailTestRoute
  '/_authenticated/admin/settings/email': typeof AuthenticatedAdminSettingsEmailRoute
  '/_authenticated/recruiter/jobs/new': typeof AuthenticatedRecruiterJobsNewRoute
  '/_authenticated/admin/campaigns/': typeof AuthenticatedAdminCampaignsIndexRoute
  '/_authenticated/admin/candidates/': typeof AuthenticatedAdminCandidatesIndexRoute
  '/_authenticated/admin/email/': typeof AuthenticatedAdminEmailIndexRoute
  '/_authenticated/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/_authenticated/admin/recruiters/': typeof AuthenticatedAdminRecruitersIndexRoute
  '/_authenticated/admin/revenue/': typeof AuthenticatedAdminRevenueIndexRoute
  '/_authenticated/recruiter/pricing/': typeof AuthenticatedRecruiterPricingIndexRoute
  '/_authenticated/admin/email/campaigns/$campaignId': typeof AuthenticatedAdminEmailCampaignsCampaignIdRoute
  '/_authenticated/admin/email/campaigns/new': typeof AuthenticatedAdminEmailCampaignsNewRoute
  '/_authenticated/admin/email/templates/$templateId': typeof AuthenticatedAdminEmailTemplatesTemplateIdRoute
  '/_authenticated/recruiter/jobs/$jobId/applicants': typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
  '/_authenticated/recruiter/jobs/$jobId/edit': typeof AuthenticatedRecruiterJobsJobIdEditRoute
  '/_authenticated/admin/email/campaigns/': typeof AuthenticatedAdminEmailCampaignsIndexRoute
  '/_authenticated/admin/email/templates/': typeof AuthenticatedAdminEmailTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/unsubscribe'
    | '/admin'
    | '/candidate'
    | '/recruiter'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apply/sign-in'
    | '/apply/sign-up'
    | '/hire/sign-in'
    | '/hire/sign-up'
    | '/jobs/$slug'
    | '/staff/sign-in'
    | '/jobs/'
    | '/candidate/applications'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/admin/'
    | '/apps/'
    | '/candidate/'
    | '/chats/'
    | '/dashboard/'
    | '/help-center/'
    | '/recruiter/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/admin/email/analytics'
    | '/admin/email/automations'
    | '/admin/email/test'
    | '/admin/settings/email'
    | '/recruiter/jobs/new'
    | '/admin/campaigns/'
    | '/admin/candidates/'
    | '/admin/email/'
    | '/admin/jobs/'
    | '/admin/recruiters/'
    | '/admin/revenue/'
    | '/recruiter/pricing/'
    | '/admin/email/campaigns/$campaignId'
    | '/admin/email/campaigns/new'
    | '/admin/email/templates/$templateId'
    | '/recruiter/jobs/$jobId/applicants'
    | '/recruiter/jobs/$jobId/edit'
    | '/admin/email/campaigns/'
    | '/admin/email/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unsubscribe'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apply/sign-in'
    | '/apply/sign-up'
    | '/hire/sign-in'
    | '/hire/sign-up'
    | '/jobs/$slug'
    | '/staff/sign-in'
    | '/jobs'
    | '/candidate/applications'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/admin'
    | '/apps'
    | '/candidate'
    | '/chats'
    | '/dashboard'
    | '/help-center'
    | '/recruiter'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/admin/email/analytics'
    | '/admin/email/automations'
    | '/admin/email/test'
    | '/admin/settings/email'
    | '/recruiter/jobs/new'
    | '/admin/campaigns'
    | '/admin/candidates'
    | '/admin/email'
    | '/admin/jobs'
    | '/admin/recruiters'
    | '/admin/revenue'
    | '/recruiter/pricing'
    | '/admin/email/campaigns/$campaignId'
    | '/admin/email/campaigns/new'
    | '/admin/email/templates/$templateId'
    | '/recruiter/jobs/$jobId/applicants'
    | '/recruiter/jobs/$jobId/edit'
    | '/admin/email/campaigns'
    | '/admin/email/templates'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/jobs'
    | '/unsubscribe'
    | '/_authenticated/admin'
    | '/_authenticated/candidate'
    | '/_authenticated/recruiter'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/apply/sign-in'
    | '/apply/sign-up'
    | '/hire/sign-in'
    | '/hire/sign-up'
    | '/jobs/$slug'
    | '/staff/sign-in'
    | '/jobs/'
    | '/_authenticated/candidate/applications'
    | '/_authenticated/candidate/profile'
    | '/_authenticated/candidate/resume'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/admin/'
    | '/_authenticated/apps/'
    | '/_authenticated/candidate/'
    | '/_authenticated/chats/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/help-center/'
    | '/_authenticated/recruiter/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/email/analytics'
    | '/_authenticated/admin/email/automations'
    | '/_authenticated/admin/email/test'
    | '/_authenticated/admin/settings/email'
    | '/_authenticated/recruiter/jobs/new'
    | '/_authenticated/admin/campaigns/'
    | '/_authenticated/admin/candidates/'
    | '/_authenticated/admin/email/'
    | '/_authenticated/admin/jobs/'
    | '/_authenticated/admin/recruiters/'
    | '/_authenticated/admin/revenue/'
    | '/_authenticated/recruiter/pricing/'
    | '/_authenticated/admin/email/campaigns/$campaignId'
    | '/_authenticated/admin/email/campaigns/new'
    | '/_authenticated/admin/email/templates/$templateId'
    | '/_authenticated/recruiter/jobs/$jobId/applicants'
    | '/_authenticated/recruiter/jobs/$jobId/edit'
    | '/_authenticated/admin/email/campaigns/'
    | '/_authenticated/admin/email/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  JobsRouteRoute: typeof JobsRouteRouteWithChildren
  UnsubscribeRoute: typeof UnsubscribeRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ApplySignInRoute: typeof ApplySignInRoute
  ApplySignUpRoute: typeof ApplySignUpRoute
  HireSignInRoute: typeof HireSignInRoute
  HireSignUpRoute: typeof HireSignUpRoute
  StaffSignInRoute: typeof StaffSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/staff/sign-in': {
      id: '/staff/sign-in'
      path: '/staff/sign-in'
      fullPath: '/staff/sign-in'
      preLoaderRoute: typeof StaffSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/hire/sign-up': {
      id: '/hire/sign-up'
      path: '/hire/sign-up'
      fullPath: '/hire/sign-up'
      preLoaderRoute: typeof HireSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/sign-in': {
      id: '/hire/sign-in'
      path: '/hire/sign-in'
      fullPath: '/hire/sign-in'
      preLoaderRoute: typeof HireSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/sign-up': {
      id: '/apply/sign-up'
      path: '/apply/sign-up'
      fullPath: '/apply/sign-up'
      preLoaderRoute: typeof ApplySignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/sign-in': {
      id: '/apply/sign-in'
      path: '/apply/sign-in'
      fullPath: '/apply/sign-in'
      preLoaderRoute: typeof ApplySignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter': {
      id: '/_authenticated/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof AuthenticatedRecruiterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate': {
      id: '/_authenticated/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof AuthenticatedCandidateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/recruiter/': {
      id: '/_authenticated/recruiter/'
      path: '/'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AuthenticatedRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/': {
      id: '/_authenticated/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AuthenticatedCandidateIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/resume': {
      id: '/_authenticated/candidate/resume'
      path: '/resume'
      fullPath: '/candidate/resume'
      preLoaderRoute: typeof AuthenticatedCandidateResumeRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/profile': {
      id: '/_authenticated/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof AuthenticatedCandidateProfileRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/applications': {
      id: '/_authenticated/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/recruiter/pricing/': {
      id: '/_authenticated/recruiter/pricing/'
      path: '/pricing'
      fullPath: '/recruiter/pricing/'
      preLoaderRoute: typeof AuthenticatedRecruiterPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/admin/revenue/': {
      id: '/_authenticated/admin/revenue/'
      path: '/revenue'
      fullPath: '/admin/revenue/'
      preLoaderRoute: typeof AuthenticatedAdminRevenueIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/recruiters/': {
      id: '/_authenticated/admin/recruiters/'
      path: '/recruiters'
      fullPath: '/admin/recruiters/'
      preLoaderRoute: typeof AuthenticatedAdminRecruitersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/jobs/': {
      id: '/_authenticated/admin/jobs/'
      path: '/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedAdminJobsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/': {
      id: '/_authenticated/admin/email/'
      path: '/email'
      fullPath: '/admin/email/'
      preLoaderRoute: typeof AuthenticatedAdminEmailIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/candidates/': {
      id: '/_authenticated/admin/candidates/'
      path: '/candidates'
      fullPath: '/admin/candidates/'
      preLoaderRoute: typeof AuthenticatedAdminCandidatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns/': {
      id: '/_authenticated/admin/campaigns/'
      path: '/campaigns'
      fullPath: '/admin/campaigns/'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/recruiter/jobs/new': {
      id: '/_authenticated/recruiter/jobs/new'
      path: '/jobs/new'
      fullPath: '/recruiter/jobs/new'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsNewRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/admin/settings/email': {
      id: '/_authenticated/admin/settings/email'
      path: '/settings/email'
      fullPath: '/admin/settings/email'
      preLoaderRoute: typeof AuthenticatedAdminSettingsEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/test': {
      id: '/_authenticated/admin/email/test'
      path: '/email/test'
      fullPath: '/admin/email/test'
      preLoaderRoute: typeof AuthenticatedAdminEmailTestRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/automations': {
      id: '/_authenticated/admin/email/automations'
      path: '/email/automations'
      fullPath: '/admin/email/automations'
      preLoaderRoute: typeof AuthenticatedAdminEmailAutomationsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/analytics': {
      id: '/_authenticated/admin/email/analytics'
      path: '/email/analytics'
      fullPath: '/admin/email/analytics'
      preLoaderRoute: typeof AuthenticatedAdminEmailAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/templates/': {
      id: '/_authenticated/admin/email/templates/'
      path: '/email/templates'
      fullPath: '/admin/email/templates/'
      preLoaderRoute: typeof AuthenticatedAdminEmailTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/campaigns/': {
      id: '/_authenticated/admin/email/campaigns/'
      path: '/email/campaigns'
      fullPath: '/admin/email/campaigns/'
      preLoaderRoute: typeof AuthenticatedAdminEmailCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/recruiter/jobs/$jobId/edit': {
      id: '/_authenticated/recruiter/jobs/$jobId/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/recruiter/jobs/$jobId/edit'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsJobIdEditRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/recruiter/jobs/$jobId/applicants': {
      id: '/_authenticated/recruiter/jobs/$jobId/applicants'
      path: '/jobs/$jobId/applicants'
      fullPath: '/recruiter/jobs/$jobId/applicants'
      preLoaderRoute: typeof AuthenticatedRecruiterJobsJobIdApplicantsRouteImport
      parentRoute: typeof AuthenticatedRecruiterRouteRoute
    }
    '/_authenticated/admin/email/templates/$templateId': {
      id: '/_authenticated/admin/email/templates/$templateId'
      path: '/email/templates/$templateId'
      fullPath: '/admin/email/templates/$templateId'
      preLoaderRoute: typeof AuthenticatedAdminEmailTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/campaigns/new': {
      id: '/_authenticated/admin/email/campaigns/new'
      path: '/email/campaigns/new'
      fullPath: '/admin/email/campaigns/new'
      preLoaderRoute: typeof AuthenticatedAdminEmailCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email/campaigns/$campaignId': {
      id: '/_authenticated/admin/email/campaigns/$campaignId'
      path: '/email/campaigns/$campaignId'
      fullPath: '/admin/email/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedAdminEmailCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminEmailAnalyticsRoute: typeof AuthenticatedAdminEmailAnalyticsRoute
  AuthenticatedAdminEmailAutomationsRoute: typeof AuthenticatedAdminEmailAutomationsRoute
  AuthenticatedAdminEmailTestRoute: typeof AuthenticatedAdminEmailTestRoute
  AuthenticatedAdminSettingsEmailRoute: typeof AuthenticatedAdminSettingsEmailRoute
  AuthenticatedAdminCampaignsIndexRoute: typeof AuthenticatedAdminCampaignsIndexRoute
  AuthenticatedAdminCandidatesIndexRoute: typeof AuthenticatedAdminCandidatesIndexRoute
  AuthenticatedAdminEmailIndexRoute: typeof AuthenticatedAdminEmailIndexRoute
  AuthenticatedAdminJobsIndexRoute: typeof AuthenticatedAdminJobsIndexRoute
  AuthenticatedAdminRecruitersIndexRoute: typeof AuthenticatedAdminRecruitersIndexRoute
  AuthenticatedAdminRevenueIndexRoute: typeof AuthenticatedAdminRevenueIndexRoute
  AuthenticatedAdminEmailCampaignsCampaignIdRoute: typeof AuthenticatedAdminEmailCampaignsCampaignIdRoute
  AuthenticatedAdminEmailCampaignsNewRoute: typeof AuthenticatedAdminEmailCampaignsNewRoute
  AuthenticatedAdminEmailTemplatesTemplateIdRoute: typeof AuthenticatedAdminEmailTemplatesTemplateIdRoute
  AuthenticatedAdminEmailCampaignsIndexRoute: typeof AuthenticatedAdminEmailCampaignsIndexRoute
  AuthenticatedAdminEmailTemplatesIndexRoute: typeof AuthenticatedAdminEmailTemplatesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminEmailAnalyticsRoute:
      AuthenticatedAdminEmailAnalyticsRoute,
    AuthenticatedAdminEmailAutomationsRoute:
      AuthenticatedAdminEmailAutomationsRoute,
    AuthenticatedAdminEmailTestRoute: AuthenticatedAdminEmailTestRoute,
    AuthenticatedAdminSettingsEmailRoute: AuthenticatedAdminSettingsEmailRoute,
    AuthenticatedAdminCampaignsIndexRoute:
      AuthenticatedAdminCampaignsIndexRoute,
    AuthenticatedAdminCandidatesIndexRoute:
      AuthenticatedAdminCandidatesIndexRoute,
    AuthenticatedAdminEmailIndexRoute: AuthenticatedAdminEmailIndexRoute,
    AuthenticatedAdminJobsIndexRoute: AuthenticatedAdminJobsIndexRoute,
    AuthenticatedAdminRecruitersIndexRoute:
      AuthenticatedAdminRecruitersIndexRoute,
    AuthenticatedAdminRevenueIndexRoute: AuthenticatedAdminRevenueIndexRoute,
    AuthenticatedAdminEmailCampaignsCampaignIdRoute:
      AuthenticatedAdminEmailCampaignsCampaignIdRoute,
    AuthenticatedAdminEmailCampaignsNewRoute:
      AuthenticatedAdminEmailCampaignsNewRoute,
    AuthenticatedAdminEmailTemplatesTemplateIdRoute:
      AuthenticatedAdminEmailTemplatesTemplateIdRoute,
    AuthenticatedAdminEmailCampaignsIndexRoute:
      AuthenticatedAdminEmailCampaignsIndexRoute,
    AuthenticatedAdminEmailTemplatesIndexRoute:
      AuthenticatedAdminEmailTemplatesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCandidateRouteRouteChildren {
  AuthenticatedCandidateApplicationsRoute: typeof AuthenticatedCandidateApplicationsRoute
  AuthenticatedCandidateProfileRoute: typeof AuthenticatedCandidateProfileRoute
  AuthenticatedCandidateResumeRoute: typeof AuthenticatedCandidateResumeRoute
  AuthenticatedCandidateIndexRoute: typeof AuthenticatedCandidateIndexRoute
}

const AuthenticatedCandidateRouteRouteChildren: AuthenticatedCandidateRouteRouteChildren =
  {
    AuthenticatedCandidateApplicationsRoute:
      AuthenticatedCandidateApplicationsRoute,
    AuthenticatedCandidateProfileRoute: AuthenticatedCandidateProfileRoute,
    AuthenticatedCandidateResumeRoute: AuthenticatedCandidateResumeRoute,
    AuthenticatedCandidateIndexRoute: AuthenticatedCandidateIndexRoute,
  }

const AuthenticatedCandidateRouteRouteWithChildren =
  AuthenticatedCandidateRouteRoute._addFileChildren(
    AuthenticatedCandidateRouteRouteChildren,
  )

interface AuthenticatedRecruiterRouteRouteChildren {
  AuthenticatedRecruiterIndexRoute: typeof AuthenticatedRecruiterIndexRoute
  AuthenticatedRecruiterJobsNewRoute: typeof AuthenticatedRecruiterJobsNewRoute
  AuthenticatedRecruiterPricingIndexRoute: typeof AuthenticatedRecruiterPricingIndexRoute
  AuthenticatedRecruiterJobsJobIdApplicantsRoute: typeof AuthenticatedRecruiterJobsJobIdApplicantsRoute
  AuthenticatedRecruiterJobsJobIdEditRoute: typeof AuthenticatedRecruiterJobsJobIdEditRoute
}

const AuthenticatedRecruiterRouteRouteChildren: AuthenticatedRecruiterRouteRouteChildren =
  {
    AuthenticatedRecruiterIndexRoute: AuthenticatedRecruiterIndexRoute,
    AuthenticatedRecruiterJobsNewRoute: AuthenticatedRecruiterJobsNewRoute,
    AuthenticatedRecruiterPricingIndexRoute:
      AuthenticatedRecruiterPricingIndexRoute,
    AuthenticatedRecruiterJobsJobIdApplicantsRoute:
      AuthenticatedRecruiterJobsJobIdApplicantsRoute,
    AuthenticatedRecruiterJobsJobIdEditRoute:
      AuthenticatedRecruiterJobsJobIdEditRoute,
  }

const AuthenticatedRecruiterRouteRouteWithChildren =
  AuthenticatedRecruiterRouteRoute._addFileChildren(
    AuthenticatedRecruiterRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCandidateRouteRoute: typeof AuthenticatedCandidateRouteRouteWithChildren
  AuthenticatedRecruiterRouteRoute: typeof AuthenticatedRecruiterRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCandidateRouteRoute:
    AuthenticatedCandidateRouteRouteWithChildren,
  AuthenticatedRecruiterRouteRoute:
    AuthenticatedRecruiterRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JobsRouteRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteRouteChildren: JobsRouteRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteRouteWithChildren = JobsRouteRoute._addFileChildren(
  JobsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  JobsRouteRoute: JobsRouteRouteWithChildren,
  UnsubscribeRoute: UnsubscribeRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ApplySignInRoute: ApplySignInRoute,
  ApplySignUpRoute: ApplySignUpRoute,
  HireSignInRoute: HireSignInRoute,
  HireSignUpRoute: HireSignUpRoute,
  StaffSignInRoute: StaffSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
