/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteRouteImport } from './routes/jobs/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as StaffSignInRouteImport } from './routes/staff/sign-in'
import { Route as JobsSlugRouteImport } from './routes/jobs/$slug'
import { Route as HireSignUpRouteImport } from './routes/hire/sign-up'
import { Route as HireSignInRouteImport } from './routes/hire/sign-in'
import { Route as ApplySignUpRouteImport } from './routes/apply/sign-up'
import { Route as ApplySignInRouteImport } from './routes/apply/sign-in'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedCandidateRouteRouteImport } from './routes/_authenticated/candidate/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRecruiterIndexRouteImport } from './routes/_authenticated/recruiter/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCandidateIndexRouteImport } from './routes/_authenticated/candidate/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCandidateResumeRouteImport } from './routes/_authenticated/candidate/resume'
import { Route as AuthenticatedCandidateProfileRouteImport } from './routes/_authenticated/candidate/profile'
import { Route as AuthenticatedCandidateApplicationsRouteImport } from './routes/_authenticated/candidate/applications'
import { Route as AuthenticatedRecruiterPricingIndexRouteImport } from './routes/_authenticated/recruiter/pricing/index'
import { Route as AuthenticatedAdminJobsIndexRouteImport } from './routes/_authenticated/admin/jobs/index'

const JobsRouteRoute = JobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRouteRoute,
} as any)
const StaffSignInRoute = StaffSignInRouteImport.update({
  id: '/staff/sign-in',
  path: '/staff/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRouteRoute,
} as any)
const HireSignUpRoute = HireSignUpRouteImport.update({
  id: '/hire/sign-up',
  path: '/hire/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const HireSignInRoute = HireSignInRouteImport.update({
  id: '/hire/sign-in',
  path: '/hire/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySignUpRoute = ApplySignUpRouteImport.update({
  id: '/apply/sign-up',
  path: '/apply/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplySignInRoute = ApplySignInRouteImport.update({
  id: '/apply/sign-in',
  path: '/apply/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateRouteRoute =
  AuthenticatedCandidateRouteRouteImport.update({
    id: '/candidate',
    path: '/candidate',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRecruiterIndexRoute =
  AuthenticatedRecruiterIndexRouteImport.update({
    id: '/recruiter/',
    path: '/recruiter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidateIndexRoute =
  AuthenticatedCandidateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCandidateResumeRoute =
  AuthenticatedCandidateResumeRouteImport.update({
    id: '/resume',
    path: '/resume',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateProfileRoute =
  AuthenticatedCandidateProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedCandidateApplicationsRoute =
  AuthenticatedCandidateApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedCandidateRouteRoute,
  } as any)
const AuthenticatedRecruiterPricingIndexRoute =
  AuthenticatedRecruiterPricingIndexRouteImport.update({
    id: '/recruiter/pricing/',
    path: '/recruiter/pricing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminJobsIndexRoute =
  AuthenticatedAdminJobsIndexRouteImport.update({
    id: '/admin/jobs/',
    path: '/admin/jobs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jobs': typeof JobsRouteRouteWithChildren
  '/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apply/sign-in': typeof ApplySignInRoute
  '/apply/sign-up': typeof ApplySignUpRoute
  '/hire/sign-in': typeof HireSignInRoute
  '/hire/sign-up': typeof HireSignUpRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/jobs/': typeof JobsIndexRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/resume': typeof AuthenticatedCandidateResumeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/recruiter/pricing/': typeof AuthenticatedRecruiterPricingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/apply/sign-in': typeof ApplySignInRoute
  '/apply/sign-up': typeof ApplySignUpRoute
  '/hire/sign-in': typeof HireSignInRoute
  '/hire/sign-up': typeof HireSignUpRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/jobs': typeof JobsIndexRoute
  '/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/candidate/resume': typeof AuthenticatedCandidateResumeRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/candidate': typeof AuthenticatedCandidateIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/recruiter': typeof AuthenticatedRecruiterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsIndexRoute
  '/recruiter/pricing': typeof AuthenticatedRecruiterPricingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/jobs': typeof JobsRouteRouteWithChildren
  '/_authenticated/candidate': typeof AuthenticatedCandidateRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/apply/sign-in': typeof ApplySignInRoute
  '/apply/sign-up': typeof ApplySignUpRoute
  '/hire/sign-in': typeof HireSignInRoute
  '/hire/sign-up': typeof HireSignUpRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/staff/sign-in': typeof StaffSignInRoute
  '/jobs/': typeof JobsIndexRoute
  '/_authenticated/candidate/applications': typeof AuthenticatedCandidateApplicationsRoute
  '/_authenticated/candidate/profile': typeof AuthenticatedCandidateProfileRoute
  '/_authenticated/candidate/resume': typeof AuthenticatedCandidateResumeRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/candidate/': typeof AuthenticatedCandidateIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/recruiter/': typeof AuthenticatedRecruiterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/admin/jobs/': typeof AuthenticatedAdminJobsIndexRoute
  '/_authenticated/recruiter/pricing/': typeof AuthenticatedRecruiterPricingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jobs'
    | '/candidate'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apply/sign-in'
    | '/apply/sign-up'
    | '/hire/sign-in'
    | '/hire/sign-up'
    | '/jobs/$slug'
    | '/staff/sign-in'
    | '/jobs/'
    | '/candidate/applications'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/admin/'
    | '/apps/'
    | '/candidate/'
    | '/chats/'
    | '/dashboard/'
    | '/help-center/'
    | '/recruiter/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/admin/jobs/'
    | '/recruiter/pricing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/apply/sign-in'
    | '/apply/sign-up'
    | '/hire/sign-in'
    | '/hire/sign-up'
    | '/jobs/$slug'
    | '/staff/sign-in'
    | '/jobs'
    | '/candidate/applications'
    | '/candidate/profile'
    | '/candidate/resume'
    | '/errors/$error'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/admin'
    | '/apps'
    | '/candidate'
    | '/chats'
    | '/dashboard'
    | '/help-center'
    | '/recruiter'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/admin/jobs'
    | '/recruiter/pricing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/jobs'
    | '/_authenticated/candidate'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/apply/sign-in'
    | '/apply/sign-up'
    | '/hire/sign-in'
    | '/hire/sign-up'
    | '/jobs/$slug'
    | '/staff/sign-in'
    | '/jobs/'
    | '/_authenticated/candidate/applications'
    | '/_authenticated/candidate/profile'
    | '/_authenticated/candidate/resume'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/admin/'
    | '/_authenticated/apps/'
    | '/_authenticated/candidate/'
    | '/_authenticated/chats/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/help-center/'
    | '/_authenticated/recruiter/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/admin/jobs/'
    | '/_authenticated/recruiter/pricing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  JobsRouteRoute: typeof JobsRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ApplySignInRoute: typeof ApplySignInRoute
  ApplySignUpRoute: typeof ApplySignUpRoute
  HireSignInRoute: typeof HireSignInRoute
  HireSignUpRoute: typeof HireSignUpRoute
  StaffSignInRoute: typeof StaffSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/staff/sign-in': {
      id: '/staff/sign-in'
      path: '/staff/sign-in'
      fullPath: '/staff/sign-in'
      preLoaderRoute: typeof StaffSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRouteRoute
    }
    '/hire/sign-up': {
      id: '/hire/sign-up'
      path: '/hire/sign-up'
      fullPath: '/hire/sign-up'
      preLoaderRoute: typeof HireSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/sign-in': {
      id: '/hire/sign-in'
      path: '/hire/sign-in'
      fullPath: '/hire/sign-in'
      preLoaderRoute: typeof HireSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/sign-up': {
      id: '/apply/sign-up'
      path: '/apply/sign-up'
      fullPath: '/apply/sign-up'
      preLoaderRoute: typeof ApplySignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/sign-in': {
      id: '/apply/sign-in'
      path: '/apply/sign-in'
      fullPath: '/apply/sign-in'
      preLoaderRoute: typeof ApplySignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate': {
      id: '/_authenticated/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof AuthenticatedCandidateRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/recruiter/': {
      id: '/_authenticated/recruiter/'
      path: '/recruiter'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AuthenticatedRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/': {
      id: '/_authenticated/candidate/'
      path: '/'
      fullPath: '/candidate/'
      preLoaderRoute: typeof AuthenticatedCandidateIndexRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidate/resume': {
      id: '/_authenticated/candidate/resume'
      path: '/resume'
      fullPath: '/candidate/resume'
      preLoaderRoute: typeof AuthenticatedCandidateResumeRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/profile': {
      id: '/_authenticated/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof AuthenticatedCandidateProfileRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/candidate/applications': {
      id: '/_authenticated/candidate/applications'
      path: '/applications'
      fullPath: '/candidate/applications'
      preLoaderRoute: typeof AuthenticatedCandidateApplicationsRouteImport
      parentRoute: typeof AuthenticatedCandidateRouteRoute
    }
    '/_authenticated/recruiter/pricing/': {
      id: '/_authenticated/recruiter/pricing/'
      path: '/recruiter/pricing'
      fullPath: '/recruiter/pricing/'
      preLoaderRoute: typeof AuthenticatedRecruiterPricingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/jobs/': {
      id: '/_authenticated/admin/jobs/'
      path: '/admin/jobs'
      fullPath: '/admin/jobs/'
      preLoaderRoute: typeof AuthenticatedAdminJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCandidateRouteRouteChildren {
  AuthenticatedCandidateApplicationsRoute: typeof AuthenticatedCandidateApplicationsRoute
  AuthenticatedCandidateProfileRoute: typeof AuthenticatedCandidateProfileRoute
  AuthenticatedCandidateResumeRoute: typeof AuthenticatedCandidateResumeRoute
  AuthenticatedCandidateIndexRoute: typeof AuthenticatedCandidateIndexRoute
}

const AuthenticatedCandidateRouteRouteChildren: AuthenticatedCandidateRouteRouteChildren =
  {
    AuthenticatedCandidateApplicationsRoute:
      AuthenticatedCandidateApplicationsRoute,
    AuthenticatedCandidateProfileRoute: AuthenticatedCandidateProfileRoute,
    AuthenticatedCandidateResumeRoute: AuthenticatedCandidateResumeRoute,
    AuthenticatedCandidateIndexRoute: AuthenticatedCandidateIndexRoute,
  }

const AuthenticatedCandidateRouteRouteWithChildren =
  AuthenticatedCandidateRouteRoute._addFileChildren(
    AuthenticatedCandidateRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCandidateRouteRoute: typeof AuthenticatedCandidateRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedRecruiterIndexRoute: typeof AuthenticatedRecruiterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedAdminJobsIndexRoute: typeof AuthenticatedAdminJobsIndexRoute
  AuthenticatedRecruiterPricingIndexRoute: typeof AuthenticatedRecruiterPricingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCandidateRouteRoute:
    AuthenticatedCandidateRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedRecruiterIndexRoute: AuthenticatedRecruiterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedAdminJobsIndexRoute: AuthenticatedAdminJobsIndexRoute,
  AuthenticatedRecruiterPricingIndexRoute:
    AuthenticatedRecruiterPricingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface JobsRouteRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteRouteChildren: JobsRouteRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteRouteWithChildren = JobsRouteRoute._addFileChildren(
  JobsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  JobsRouteRoute: JobsRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ApplySignInRoute: ApplySignInRoute,
  ApplySignUpRoute: ApplySignUpRoute,
  HireSignInRoute: HireSignInRoute,
  HireSignUpRoute: HireSignUpRoute,
  StaffSignInRoute: StaffSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
