-- Atomic fixed-window quotas for public/serverless API routes.
-- Keys are SHA-256 hashes generated by the API; raw IPs/emails are never stored.

CREATE TABLE IF NOT EXISTS public.api_rate_limits (
  key_hash TEXT PRIMARY KEY,
  request_count INTEGER NOT NULL,
  window_expires_at TIMESTAMPTZ NOT NULL,
  CONSTRAINT api_rate_limits_key_hash_format CHECK (key_hash ~ '^[0-9a-f]{64}$'),
  CONSTRAINT api_rate_limits_request_count_positive CHECK (request_count > 0)
);

CREATE INDEX IF NOT EXISTS api_rate_limits_window_expires_at_idx
ON public.api_rate_limits (window_expires_at);

ALTER TABLE public.api_rate_limits ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.api_rate_limits FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.consume_api_rate_limit (
  p_key_hash TEXT,
  p_limit INTEGER,
  p_window_seconds INTEGER
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_now TIMESTAMPTZ := clock_timestamp();
  v_count INTEGER;
BEGIN
  IF p_key_hash !~ '^[0-9a-f]{64}$' THEN
    RAISE EXCEPTION 'invalid rate-limit key';
  END IF;
  IF p_limit < 1 OR p_limit > 10000 THEN
    RAISE EXCEPTION 'invalid rate-limit limit';
  END IF;
  IF p_window_seconds < 1 OR p_window_seconds > 86400 THEN
    RAISE EXCEPTION 'invalid rate-limit window';
  END IF;

  INSERT INTO public.api_rate_limits AS limits (
    key_hash,
    request_count,
    window_expires_at
  )
  VALUES (
    p_key_hash,
    1,
    v_now + make_interval(secs => p_window_seconds)
  )
  ON CONFLICT (key_hash) DO UPDATE
  SET
    request_count = CASE
      WHEN limits.window_expires_at <= v_now THEN 1
      ELSE limits.request_count + 1
    END,
    window_expires_at = CASE
      WHEN limits.window_expires_at <= v_now
        THEN v_now + make_interval(secs => p_window_seconds)
      ELSE limits.window_expires_at
    END
  RETURNING request_count INTO v_count;

  -- Amortized cleanup keeps the table bounded without adding a cron dependency.
  IF random() < 0.02 THEN
    DELETE FROM public.api_rate_limits
    WHERE key_hash IN (
      SELECT key_hash
      FROM public.api_rate_limits
      WHERE window_expires_at < v_now - interval '1 day'
      ORDER BY window_expires_at
      LIMIT 100
    );
  END IF;

  RETURN v_count <= p_limit;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_api_rate_limit (TEXT, INTEGER, INTEGER) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.consume_api_rate_limit (TEXT, INTEGER, INTEGER) FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_api_rate_limit (TEXT, INTEGER, INTEGER) TO service_role;
